/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MVC.view;

/**
 *
 * @author Heinz
 */
public class BerandaView extends javax.swing.JPanel {

    /** Creates new form HomePanel */
    public BerandaView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 204));
        setPreferredSize(new java.awt.Dimension(1050, 404));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Halo Selamat Datang Di Aplikasi Rental Mobil");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 920, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MVC/image/20945933.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Created By ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 274, 34));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Rizma Berliana Putri Affandi");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 440, 210, 40));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Muhammad Fahmi Prasetio");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 410, 210, 32));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MVC/image/unsikuy.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
